######################################################################
# Automatically generated by qmake (3.1) Thu Jul 20 12:38:03 2023
######################################################################

QT -= core gui

TEMPLATE = app

TARGET = JuegoNave

INCLUDEPATH += ..\SDL2\x86_64-w64-mingw32\include

LIBS += -L..\SDL2\x86_64-w64-mingw32\lib

LIBS += -w -Wl,-subsystem,windows -lmingw32 -lSDL2main -lSDL2

# Input
SOURCES += \
    main.c
